FROM python:3.14-slim

WORKDIR /usr/src/app

COPY ./app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app .

RUN useradd -m -u 1000 appuser
RUN chown -R appuser:appuser /usr/src/app
USER appuser

CMD ["python", "./src/main.py", "./config/consumer.ini"]